### ISSUE TITLE
Doesn't change anything 

### ISSUE THREAD

**Issue by outfrost** [dkisselev/ZenTime#1]
I set my custom time periods and the system UI didn't change, still can't choose 6hrs etc.

Using OnePlus One with @Sultanxda's CM12.1 (5.1.1).

**Comment by dkisselev** [comment]
I've moved onto CM13 but I'll try to spin up a CM12.1 VM this week and see if I can work out what's going wrong.

In the meantime, could you please check your xposed log (it's an option in the installer) and see if here are any errors/exceptions related to zentime in there?

Thanks!

**Comment by outfrost** [comment]
Just reinstalled ZenTime, configured and rebooted, this is what comes up in the log: http://pastebin.com/raw/Re2wHWzy

**Comment by dkisselev** [comment]
Thanks for going through all those steps, that definitely helps weed out issues.

What xposed version are you running? Systemless?

I get the same error on my CM13 phone, so it's probably an issue with recent versions of the framework. I'll get back to you when I get a chance to play with it.

**Comment by outfrost** [comment]
Xposed is 3.0 alpha4. I have no idea if I have systemless root, didn't pay attention while flashing SuperSU.

**Comment by dkisselev** [comment]
What's the framework version? (it should be visible at the top of the 'Framework' section of the Xposed Installer app)

I meant systemless xposed, but if you didn't knowingly go for systemless you probably have the regular version.

**Comment by outfrost** [comment]
Sorry, my bad, that was noobish of me ;D edited my comment above.

Oh, okay. Well, I just went with the newest zip from [here](http://dl-xda.xposed.info/framework/sdk22/arm/) and flashed away.

**Comment by dkisselev** [comment]
Hey @outfrost, I've tweaked a few things in the package and updated the modules xposed api version.

It's working for me, but give this apk a test and let me know if it works for you before I publish the changes. You should be able to just install it right over your existing version. Be sure to backup your list of custom times to save yourself from needing to re-enter them if there are any issues.

https://dl2.pushbulletusercontent.com/oqxWCfdLdU8jsNkzCAzG3deh7FM0SyB8/zentime-0.2-rc1.apk

**Comment by outfrost** [comment]
Yay, it works! ^^ :D [screenshot](https://dl2.pushbulletusercontent.com/f8bjP9q40yl1hGD6DdVWHjNSKFrJ8jzH/Screenshot_2016-07-26-03-44-31.png)
Update was smooth and the list of custom times stayed in place. And now it does what it's supposed to :) Nice work.

Shame that Lollipop doesn't show e.g. 1h30min, but instead rounds up to the nearest hour, but that's a system thing obviously :)

**Comment by dkisselev** [comment]
That can be arranged ;) I'm in the process of moving houses right now so won't be able to do it, but I'll keep your idea in mind if I ever have an evening to fiddle with additional features for ZenTime.

I've published the updated version to xposed repo, you shouldn't need to do anything to upgrade because the APK is the same.
